### ISSUE TITLE
Suggession for Dynamic Information View

### ISSUE THREAD

**Issue by ErAshu** [carousell/pickle#20]
Hi, 
Is there any variable to hide the top view where the info written. I don't want to crossed view.
Please see the image.
![whatsapp image 2017-11-17 at 9 44 31 pm](https://user-images.githubusercontent.com/4178384/32957292-48b19d90-cbe1-11e7-8dd7-2a300b562709.jpeg)

**Comment by bcylin** [comment]
The view you marked crossed would be hidden when the [`hint`](https://carousell.github.io/pickle/Classes/ImagePickerController.html#/s:vC6Pickle21ImagePickerController4hintGSqCSo18NSAttributedString_) variable is set to `nil`.
