### ISSUE TITLE
Objective-C method conflict

### ISSUE THREAD

**Issue by DSofter** [carousell/pickle#37]
![image](https://user-images.githubusercontent.com/1687829/52031050-73bb5d80-24cf-11e9-88ac-2bd5ef3364da.png)

Like the image above. Any idea why? Thanks!

**Comment by bcylin** [comment]
It looks like your `ComposeViewController` also implements **UIImagePickerControllerDelegate** methods.

```swift
// UIImagePickerControllerDelegate, you probably can remove this one if you implements Pickle.ImagePickerControllerDelegate.
func imagePickerControllerDidCancel(_ picker: UIImagePickerController)
````

```swift
// Pickle.ImagePickerControllerDelegate
func imagePickerControllerDidCancel(_ picker: Pickle.ImagePickerController)
````

**Comment by DSofter** [comment]
@bcylin That's true! Thank you so much!
