### ISSUE TITLE
Something wrong with Carthage & Xcode 10.2

### ISSUE THREAD

**Issue by UzumakiAlfredo** [carousell/pickle#40]
Hi.

Im facing this issue when I want to use this library with Carthage.

it says: Dependency "pickle" has no shared framework schemes for any of the platforms: iOS

I tried it on two different MacBooks, other Carthage libraries does not had such issue.

I use Xcode 10.2.

It works fine with Xcode 10.1 & earlier though.

**Comment by bcylin** [comment]
Hi @UzumakiAlfredo, the shared scheme was accidentally missing on the master branch. It should be fixed by now. Please try carthage update again, or specify version `1.3.1` in the Cartfile.
