### ISSUE TITLE
Unable to get the fileUrl for selected media asset from PHAsset Object

### ISSUE THREAD

**Issue by sagar-nikam688** [carousell/pickle#55]
Thanks in advance,

Thanks for this wonderful library but i am not able to get the fileUrl for selected media object.

Also it will helpful for other users to be mentioned in readMe file

Thanks Again..

**Comment by bcylin** [comment]
> not able to get the fileUrl for selected media object.

Hi @sagar-nikam688, maybe `PHContentEditingInput` is what you are looking for?

```swift
asset.requestContentEditingInput(with: nil) { editingInput, info in
    print(editingInput?.fullSizeImageURL as Any)
}
```
